CREATE SCHEMA IF NOT EXISTS tours;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'tours' AND table_name = 'KeyPoints') THEN
        CREATE TABLE tours."KeyPoints" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
            "TourId" bigint NOT NULL,
            "Name" text NOT NULL,
            "Description" text NOT NULL,
            "Longitude" double precision NOT NULL,
            "Latitude" double precision NOT NULL,
            "ImagePath" text NOT NULL,
            "Secret" text NOT NULL,
            CONSTRAINT "PK_KeyPoints" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_KeyPoints_Tours_TourId" FOREIGN KEY ("TourId") REFERENCES tours."Tours" ("Id") ON DELETE CASCADE
        );
    END IF;
END
$$;

ALTER TABLE IF EXISTS tours."Equipment" ADD COLUMN IF NOT EXISTS "TourId" bigint NULL;
CREATE INDEX IF NOT EXISTS "IX_Equipment_TourId" ON tours."Equipment" ("TourId");
ALTER TABLE IF EXISTS tours."Equipment" ADD CONSTRAINT IF NOT EXISTS "FK_Equipment_Tours_TourId" FOREIGN KEY ("TourId") REFERENCES tours."Tours"("Id") ON DELETE SET NULL;

ALTER TABLE IF EXISTS tours."Tours" ADD COLUMN IF NOT EXISTS "DistanceInKm" double precision NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS tours."Tours" ADD COLUMN IF NOT EXISTS "Duration" jsonb;

ALTER TABLE IF EXISTS tours."KeyPoints" ADD COLUMN IF NOT EXISTS "Name" text NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS tours."KeyPoints" ADD COLUMN IF NOT EXISTS "Description" text NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS tours."KeyPoints" ADD COLUMN IF NOT EXISTS "Longitude" double precision NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS tours."KeyPoints" ADD COLUMN IF NOT EXISTS "Latitude" double precision NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS tours."KeyPoints" ADD COLUMN IF NOT EXISTS "ImagePath" text NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS tours."KeyPoints" ADD COLUMN IF NOT EXISTS "Secret" text NOT NULL DEFAULT '';

DELETE FROM tours."TouristEquipment";
DELETE FROM tours."Journals";
DELETE FROM tours."Meetups";
DELETE FROM tours."Facility";
DELETE FROM tours."Equipment";
DELETE FROM tours."AnnualAwards";
DELETE FROM tours."Monuments";
DELETE FROM tours."KeyPoints";
DELETE FROM tours."Tours";
ALTER SEQUENCE tours."Facility_Id_seq" RESTART WITH 100;
