-- Kreiraj tabele ako ne postoje (za svaki slučaj)
CREATE TABLE IF NOT EXISTS tours."ShoppingCarts" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TouristId" bigint NOT NULL,
    "LastModified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ShoppingCarts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS tours."OrderItems" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ShoppingCartId" bigint NOT NULL,
    "TourId" bigint NOT NULL,
    "TourName" text NOT NULL,
    "Price" double precision NOT NULL,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("ShoppingCartId", "Id"),
    CONSTRAINT "FK_OrderItems_ShoppingCarts_ShoppingCartId" 
        FOREIGN KEY ("ShoppingCartId") 
        REFERENCES tours."ShoppingCarts" ("Id") 
        ON DELETE CASCADE
);

-- Obriši postojeće test podatke
DELETE FROM tours."OrderItems";
DELETE FROM tours."ShoppingCarts";

-- Kreiraj test shopping cart za turista -1 (koristi se u testovima)
INSERT INTO tours."ShoppingCarts" ("Id", "TouristId", "LastModified")
VALUES (-1, -1, '2024-12-09 10:00:00+00')
ON CONFLICT DO NOTHING;