-- Kreiraj tabelu ako ne postoji
CREATE TABLE IF NOT EXISTS tours."TourPurchaseTokens" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TouristId" bigint NOT NULL,
    "TourId" bigint NOT NULL,
    "TourName" text NOT NULL,
    "Price" double precision NOT NULL,
    "PurchaseDate" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    CONSTRAINT "PK_TourPurchaseTokens" PRIMARY KEY ("Id")
);

-- Obriši postoje?e test podatke
DELETE FROM tours."TourPurchaseTokens";

-- Insert test purchase tokens for integration tests
INSERT INTO tours."TourPurchaseTokens" 
("Id", "TouristId", "TourId", "TourName", "Price", "PurchaseDate", "IsUsed")
VALUES 
(-1, 1, -3, 'Tura Pariza', 100, '2024-01-10 00:00:00+00', FALSE);

