-- Kreiraj tabelu ako ne postoji
CREATE TABLE IF NOT EXISTS tours."TourPurchaseTokens" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TouristId" bigint NOT NULL,
    "TourId" bigint NOT NULL,
    "TourName" text NOT NULL,
    "Price" double precision NOT NULL,
    "PurchaseDate" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    CONSTRAINT "PK_TourPurchaseTokens" PRIMARY KEY ("Id")
);

-- Obriši postojeæe test podatke
DELETE FROM tours."TourPurchaseTokens";

