-- Drop tables in correct order (respecting foreign keys)
DELETE FROM encounters."LeaderboardEntries";
DELETE FROM encounters."ClubLeaderboards";
DELETE FROM encounters."HiddenLocationAttempts";
DELETE FROM encounters."ActiveSocialParticipants";
DELETE FROM encounters."EncounterCompletions";
DELETE FROM encounters."SocialEncounters";
DELETE FROM encounters."TouristXpProfiles";
DELETE FROM encounters."Challenges";

-- Create ActiveSocialParticipants table if it doesn't exist
CREATE TABLE IF NOT EXISTS encounters."ActiveSocialParticipants" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SocialEncounterId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "ActivatedAt" timestamp with time zone NOT NULL,
    "LastHeartbeat" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ActiveSocialParticipants" PRIMARY KEY ("Id")
);

-- Create unique index if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE schemaname = 'encounters' 
        AND tablename = 'ActiveSocialParticipants' 
        AND indexname = 'IX_ActiveSocialParticipants_UserId_SocialEncounterId'
    ) THEN
        CREATE UNIQUE INDEX "IX_ActiveSocialParticipants_UserId_SocialEncounterId" 
        ON encounters."ActiveSocialParticipants" ("UserId", "SocialEncounterId");
    END IF;
END $$;

-- Create SocialEncounters table if it doesn't exist
CREATE TABLE IF NOT EXISTS encounters."SocialEncounters" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ChallengeId" bigint NOT NULL,
    "RequiredPeople" integer NOT NULL,
    "RadiusMeters" double precision NOT NULL,
    CONSTRAINT "PK_SocialEncounters" PRIMARY KEY ("Id")
);

-- Create unique index for SocialEncounters if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes 
        WHERE schemaname = 'encounters' 
        AND tablename = 'SocialEncounters' 
        AND indexname = 'IX_SocialEncounters_ChallengeId'
    ) THEN
        CREATE UNIQUE INDEX "IX_SocialEncounters_ChallengeId" 
        ON encounters."SocialEncounters" ("ChallengeId");
    END IF;
END $$;
